import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { Toaster } from "sonner";
import ClientProvider from "./ClientProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Josefin_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Banking Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ClientProvider>
            {children}
          </ClientProvider>
        </UserProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}